### PR TITLE
Feature: add rate limit middleware

### PR DESCRIPTION
**Pull request by devsargam**
# Pull Request Guidelines

Our guidelines for submitting a pull request.

## Before submitting a Pull Request, please make sure you have verified the following:

- [x] The commit message follows our guidelines:
  - A good commit message should be two things: meaningful and concise. It should not contain every single detail, describing each changed line—we can see all the changes in Git—but, at the same time, it should say enough to avoid ambiguity.
  - We use Microverse's commit message convention
  - The convention stablish that a commit message has to be in the present tense, imperative and lowercase.
  - Example: `fix typo in README.md`
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Currently there is no implementation for rate limit in codebase. 

Issue Number: #113

## What is the new behavior?

This PR adds functionality to use `express-rate-limit`

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications below.

## Other information

This PR is a draft feel free to give me advises regarding my code.

### CODE REVIEW

**Comment by devsargam** [comment]
@rsaz can you review it upto now?
also can you tell me how to test the implementation is working or not?

**Comment by rsaz** [comment]
> @rsaz can you review it upto now?

Replied here: https://github.com/expressots/expressots/issues/113#issuecomment-1741977085

**Review by rsaz — COMMENTED** [review]
Your code so far follows the standard, really good. You are missing two things:
1 - Look at `packages/core/src/middleware/index.ts ` to the index.ts file inside of the middleware folder and see what you're missing there.
2 - Look at the `middleware-resolver.ts` you are missing something there as well in the `middlewareRegistry` object mapping there.

When you fix these two things you can follow the steps I gave you in the issue, then if its all good submit to me for review. 

;)

**Review by rsaz — APPROVED** [review]
Well done! How was your experience testing?

**Comment by devsargam** [comment]
It was great everything went really smooth. If this project needs anymore hands I'll be always there. Are there parts that I can contribute to?

**Comment by rsaz** [comment]
> It was great everything went really smooth. If this project needs anymore hands I'll be always there. Are there parts that I can contribute to?

We are working on to be the go to framework when you think about developing backend apps in with nodejs+typescript. :) Will be very helpful you can ⭐ the project and share with your colleagues. 👍🏻 

There is lot's of things to do, but I need to laid out the tasks as we did with the middleware mechanics.

Right now, the most important thing to get it done is all unit tests for all the core package. You can find examples here: https://github.com/expressots/expressots/tree/main/packages/core/test

Thank you for your contribution, looking forward to get new updates from you. 😄

**Pull request merged**
